# YAML linting configuration
extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Allow empty lines at end of file
  empty-lines:
    max-end: 1

  # Allow more flexible indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Don't require document start marker
  document-start: disable

  # Allow truthy values like 'yes', 'no', 'on', 'off'
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false